server:
  port: 0

eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: Baghali

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}

server:
  port: 8080
