server:
  port: 0

eureka:
  client:
    registryFetchIntervalSeconds: 3
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}ZZ:############${random.int}

---
spring:
  profiles: docker
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
#
#server:
#  port: 8080
